import type { SecurityMasterRecord } from "./types";

const NASDAQ_SYMBOL_DIRECTORY = "https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt";
const NASDAQ_OTHER_LISTED = "https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt";

const SOURCE_AS_OF = "2026-06-04";

export const STATIC_SECURITY_MASTER: SecurityMasterRecord[] = [
  {
    id: "us-sp500-index",
    marketId: "us",
    kind: "fund",
    fundSubtype: "etf",
    symbol: "SPY",
    exchange: "NYSE Arca",
    name: "SPDR S&P 500 ETF Trust",
    category: "Large Blend",
    fundCompany: "State Street",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["S&P 500", "SPY", "sp500", "us-sp500-index"],
  },
  {
    id: "us-etf-voo",
    marketId: "us",
    kind: "fund",
    fundSubtype: "etf",
    symbol: "VOO",
    exchange: "NYSE Arca",
    name: "Vanguard S&P 500 ETF",
    category: "Large Blend",
    fundCompany: "Vanguard",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["Vanguard 500", "S&P 500"],
  },
  {
    id: "us-nasdaq-100",
    marketId: "us",
    kind: "fund",
    fundSubtype: "etf",
    symbol: "QQQ",
    exchange: "Nasdaq",
    name: "Invesco QQQ Trust",
    category: "Large Growth",
    fundCompany: "Invesco",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_SYMBOL_DIRECTORY,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["Nasdaq 100", "QQQ"],
  },
  {
    id: "us-dividend-value",
    marketId: "us",
    kind: "fund",
    fundSubtype: "etf",
    symbol: "SCHD",
    exchange: "NYSE Arca",
    name: "Schwab U.S. Dividend Equity ETF",
    category: "Dividend",
    fundCompany: "Schwab",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["dividend", "SCHD"],
  },
  {
    id: "us-low-volatility",
    marketId: "us",
    kind: "fund",
    fundSubtype: "etf",
    symbol: "USMV",
    exchange: "Cboe",
    name: "iShares MSCI USA Min Vol Factor ETF",
    category: "Low Volatility",
    fundCompany: "iShares",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["low volatility", "minimum volatility"],
  },
  {
    id: "us-quality-value",
    marketId: "us",
    kind: "fund",
    fundSubtype: "etf",
    symbol: "QUAL",
    exchange: "Cboe",
    name: "iShares MSCI USA Quality Factor ETF",
    category: "Factor",
    fundCompany: "iShares",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["quality", "factor"],
  },
  {
    id: "us-short-treasury",
    marketId: "us",
    kind: "fund",
    fundSubtype: "etf",
    symbol: "SGOV",
    exchange: "Nasdaq",
    name: "iShares 0-3 Month Treasury Bond ETF",
    category: "Treasury",
    fundCompany: "iShares",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_SYMBOL_DIRECTORY,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["treasury", "cash management"],
  },
  {
    id: "us-aapl",
    marketId: "us",
    kind: "stock",
    symbol: "AAPL",
    exchange: "Nasdaq",
    name: "Apple Inc.",
    sector: "Technology",
    industry: "Consumer Electronics",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_SYMBOL_DIRECTORY,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["Apple"],
  },
  {
    id: "us-msft",
    marketId: "us",
    kind: "stock",
    symbol: "MSFT",
    exchange: "Nasdaq",
    name: "Microsoft Corporation",
    sector: "Technology",
    industry: "Software",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_SYMBOL_DIRECTORY,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["Microsoft"],
  },
  {
    id: "us-nvda",
    marketId: "us",
    kind: "stock",
    symbol: "NVDA",
    exchange: "Nasdaq",
    name: "NVIDIA Corporation",
    sector: "Technology",
    industry: "Semiconductors",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_SYMBOL_DIRECTORY,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["NVIDIA"],
  },
  {
    id: "us-brkb",
    marketId: "us",
    kind: "stock",
    symbol: "BRK.B",
    exchange: "NYSE",
    name: "Berkshire Hathaway Inc. Class B",
    sector: "Financials",
    industry: "Conglomerate",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
    aliases: ["Berkshire Hathaway", "BRK-B", "BRK/B"],
  },
  {
    id: "us-jnj",
    marketId: "us",
    kind: "stock",
    symbol: "JNJ",
    exchange: "NYSE",
    name: "Johnson & Johnson",
    sector: "Healthcare",
    industry: "Pharmaceuticals",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
  },
  {
    id: "us-jpm",
    marketId: "us",
    kind: "stock",
    symbol: "JPM",
    exchange: "NYSE",
    name: "JPMorgan Chase & Co.",
    sector: "Financials",
    industry: "Banking",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
  },
  {
    id: "us-xom",
    marketId: "us",
    kind: "stock",
    symbol: "XOM",
    exchange: "NYSE",
    name: "Exxon Mobil Corporation",
    sector: "Energy",
    industry: "Integrated Energy",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
  },
  {
    id: "us-pg",
    marketId: "us",
    kind: "stock",
    symbol: "PG",
    exchange: "NYSE",
    name: "Procter & Gamble Company",
    sector: "Consumer Staples",
    industry: "Household Products",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
  },
  {
    id: "us-ko",
    marketId: "us",
    kind: "stock",
    symbol: "KO",
    exchange: "NYSE",
    name: "Coca-Cola Company",
    sector: "Consumer Staples",
    industry: "Beverages",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
  },
  {
    id: "us-v",
    marketId: "us",
    kind: "stock",
    symbol: "V",
    exchange: "NYSE",
    name: "Visa Inc.",
    sector: "Financials",
    industry: "Payments",
    sourceName: "Nasdaq Symbol Directory",
    sourceUrl: NASDAQ_OTHER_LISTED,
    sourceAsOf: SOURCE_AS_OF,
    isTradable: true,
  },
];

export const SECURITY_MASTER_SOURCE_URLS = {
  NASDAQ_SYMBOL_DIRECTORY,
  NASDAQ_OTHER_LISTED,
};
